
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PONTOVIRGULA = 20;
  public static final int DIVISOR = 5;
  public static final int SHORT = 35;
  public static final int MULTIPLICADORIGUAL = 15;
  public static final int SCANF = 47;
  public static final int CONST = 28;
  public static final int CHAR = 30;
  public static final int CHAVE_E = 52;
  public static final int CHAVE_D = 53;
  public static final int DIFERENTE = 9;
  public static final int DOUBLE = 32;
  public static final int INT = 36;
  public static final int MAISIGUAL = 18;
  public static final int MAIORIGUAL = 12;
  public static final int FOR = 42;
  public static final int VIRGULA = 21;
  public static final int PONTO = 24;
  public static final int STATIC = 26;
  public static final int DEFINE = 55;
  public static final int MENORIGUAL = 13;
  public static final int AND = 6;
  public static final int IGUAL = 14;
  public static final int OR = 7;
  public static final int MAIS = 2;
  public static final int NUM = 58;
  public static final int EXTERN = 27;
  public static final int IF = 40;
  public static final int ASPA_SIMPLES = 22;
  public static final int ID = 57;
  public static final int MULTIPLICADOR = 4;
  public static final int CRLF = 56;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int MAIOR = 11;
  public static final int error = 1;
  public static final int INCLUDE = 54;
  public static final int MENOS = 3;
  public static final int MENOR = 10;
  public static final int UNSIGNED = 34;
  public static final int AUTO = 25;
  public static final int BREAK = 44;
  public static final int VOID = 29;
  public static final int PRINTF = 46;
  public static final int MODIGUAL = 17;
  public static final int LITERAL = 59;
  public static final int COLCHETE_E = 50;
  public static final int ELSE = 41;
  public static final int COLCHETE_D = 51;
  public static final int ENUM = 38;
  public static final int SIGNED = 33;
  public static final int IGUALIGUAL = 8;
  public static final int WHILE = 43;
  public static final int PARENTESE_E = 48;
  public static final int DIVISORIGUAL = 16;
  public static final int PARENTESE_D = 49;
  public static final int FLOAT = 31;
  public static final int MENOSIGUAL = 19;
  public static final int LONG = 37;
  public static final int ASPA_DUPLA = 23;
  public static final int STRUCT = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIS",
  "MENOS",
  "MULTIPLICADOR",
  "DIVISOR",
  "AND",
  "OR",
  "IGUALIGUAL",
  "DIFERENTE",
  "MENOR",
  "MAIOR",
  "MAIORIGUAL",
  "MENORIGUAL",
  "IGUAL",
  "MULTIPLICADORIGUAL",
  "DIVISORIGUAL",
  "MODIGUAL",
  "MAISIGUAL",
  "MENOSIGUAL",
  "PONTOVIRGULA",
  "VIRGULA",
  "ASPA_SIMPLES",
  "ASPA_DUPLA",
  "PONTO",
  "AUTO",
  "STATIC",
  "EXTERN",
  "CONST",
  "VOID",
  "CHAR",
  "FLOAT",
  "DOUBLE",
  "SIGNED",
  "UNSIGNED",
  "SHORT",
  "INT",
  "LONG",
  "ENUM",
  "STRUCT",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "BREAK",
  "RETURN",
  "PRINTF",
  "SCANF",
  "PARENTESE_E",
  "PARENTESE_D",
  "COLCHETE_E",
  "COLCHETE_D",
  "CHAVE_E",
  "CHAVE_D",
  "INCLUDE",
  "DEFINE",
  "CRLF",
  "ID",
  "NUM",
  "LITERAL"
  };
}

